// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SearchTab: typeof import('./src/components/search-tab/SearchTab.vue')['default']
    SearchTabGroup: typeof import('./src/components/search-tab-group/SearchTabGroup.vue')['default']
    TreeSelect: typeof import('./src/components/tree-select/TreeSelect.vue')['default']
  }
}

export { }
